title: Learn to programing

languages:
  en: English
  pt: Portuguese

about:
  title: About

description:
  This blog aims to share my journey as a developer. Here I share my experiences
  with programming and personal projects that I have been working on in the world of technology.
