title: Learn to programing
about: About
description:
  This blog aims to share my journey as a developer. Here I share my experiences
  with programming and personal projects that I have been working on in the world of technology.
